# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
services:
  sofamous:
    image: ghcr.io/tydoo/sofamous.fr:latest
    restart: unless-stopped
    ports:
      - "443:443"
    stop_grace_period: 1h
    volumes:
      - /etc/ssl/certs/sofamous.fr.pem:/etc/ssl/certs/sofamous.fr.pem:ro
      - /etc/ssl/private/sofamous.fr.key:/etc/ssl/private/sofamous.fr.key:ro
      - ${HOME}/.ssh:/root/.ssh:ro
    command:
      - sh
      - -c
      - "APP_VERSION_FROM_ENV_FILE=$$(sed -n 's/^APP_VERSION=//p' /app/.env | tail -n 1) && echo \"Running APP_VERSION: $$APP_VERSION_FROM_ENV_FILE\" && mkdir -p config/secrets/prod && GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' git clone --depth 1 git@github.com:tydoo/Decrypt-file-prod-sofamous.fr.git /tmp/decrypt-repo && cp /tmp/decrypt-repo/prod.decrypt.private.php config/secrets/prod/prod.decrypt.private.php && rm -rf /tmp/decrypt-repo && php bin/console doctrine:migrations:migrate --no-interaction --env=prod && exec supervisord -c /etc/supervisor/supervisord.conf"
