[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:frankenphp]
command=frankenphp run --config /etc/caddy/Caddyfile --adapter caddyfile
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopasgroup=true
killasgroup=true

[program:messenger]
command=php bin/console messenger:consume async --no-interaction --env=prod
directory=/app
autostart=true
autorestart=true
startsecs=0
stopsignal=TERM
stopwaitsecs=3600
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
